version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      EUREKA_SERVER_PORT: 8761
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_EXTERNAL
      KAFKA_CREATE_TOPICS: films:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  film-service:
    build:
      context: ./film-service
      dockerfile: Dockerfile
    image: film-service
    container_name: film-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - eureka-server
      - cinema-main-service
      - film-db
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://film-db:5432/films
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2236
      FILM_SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka
      KINOPOISK_API_HEADER: X-API-KEY
      KINOPOISK_API_TOKEN: ZJ0XHNA-RDG4Z6Y-G6MPD34-CHRBV6E
      KINOPOISK_API_URL: https://api.kinopoisk.dev/v1.4
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092

  film-db:
    image: postgres:14.7-alpine
    container_name: film-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: films
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2236
    networks:
      - app-network

  cinema-main-service:
    build:
      context: ./cinema-main-service
      dockerfile: Dockerfile
    image: cinema-main-service
    container_name: cinema-main-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - cinema-db
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cinema-db:5432/cinema
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2236
      MAIN_SERVER_PORT: 8080
      FILM_API_URL: http://api-gateway:8765/film-service
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092

  cinema-db:
    image: postgres:14.7-alpine
    container_name: cinema-db
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2236
    ports:
      - "6542:5432"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
      - film-service
      - cinema-main-service
    networks:
      - app-network
    environment:
      API_GATEWAY_PORT: 8765
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka

networks:
  app-network:
    driver: bridge